### ISSUE TITLE
Push issues: MessagingService not implemented; activateForFirebase not calling subscribe on pushUser()

### ISSUE THREAD

**Issue by brucexia** [chat-sdk/chat-sdk-android#156]
Seems like the push module is not complete? We're seriously considering integrating and would be happy to contribute. Would like some instructions on how to contribute and how you plan for these fixes.

**Comment by bensmiley** [comment]
This has been fixed but we need to do some more testing before we push it to the repository. If you did want to contribute, that would be great. Have you looked at the [contributing document](https://github.com/chat-sdk/chat-sdk-ios/blob/master/CONTRIBUTING.md)? If you make a pull request, we will review and merge it. If you think anything is missing from the document let me know.

**Comment by brucexia** [comment]
Cool. There's more issues that the push token is not retrieved when starting app  and the afterAuthentication is not calling the right hook, so the pushToken is never called after user auth. I fixed those so the registering part is working but the MessagingService still not being hit. Do you have a commit number that I can look at your fix?

**Comment by brucexia** [comment]
Turned out my serverKey isn't being picked up

**Comment by brucexia** [comment]
Found the bug. Wrong string here:

**Comment by bensmiley** [comment]
Ok, I've updated the code so this will be fixed in the next release.

**Comment by brucexia** [comment]
@bensmiley what's the branch you guys are working on? I just don't want to submit pr for issues that're already fixed.

**Comment by bensmiley** [comment]
I've done this. You can see the [dev](https://github.com/chat-sdk/chat-sdk-android/tree/dev) branch.
